spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none